fixtures:
  repositories:
    report_all_the_things: https://github.com/danzilio/puppet-report_all_the_things
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    inifile: https://github.com/puppetlabs/puppetlabs-inifile
  symlinks:
    scribe_reporter: "#{source_dir}"
